export default {
  login: '/api/login',
  getAttrs: '/api/attrs',
  addAttr: '/api/attrs',
  editAttr: '/api/attrs',
  deleteAttr: '/api/attrs',
  getParams: '/api/params',
  addParam: '/api/params',
  editParam: '/api/params',
  deleteParam: '/api/params',
  getProducts: '/api/products',
  addProduct: '/api/products',
  editProduct: '/api/products',
  deleteProduct: '/api/products',
  getCates: '/api/cates',
  addCate: '/api/cates',
  editCate: '/api/cates',
  deleteCate: '/api/cates',
  getTags: '/api/tags',
  addTag: '/api/tags',
  editTag: '/api/tags',
  deleteTag: '/api/tags',
  getArticles: '/api/articles',
  addArticle: '/api/articles',
  editArticle: '/api/articles',
  deleteArticle: '/api/articles',
};
